# Default values for rearm-watcher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enabled: true

replicaCount: 1

image:
  repository: registry.relizahub.com/library/rearm-watcher-app:26.03.3@sha256:03f5a74d2dac5c1edc6bff541676e64cd5f40505aa7e2856b781aac5a67ebe52
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

createServiceAccount: true

namespace: allnamespaces
sender: default

rearmUri: "" # must be defined

create_secret_in_chart: none # or "regular" for plane secret or "sealed" for bitnami sealed secrets
rearmApiId: placeholder
rearmApiKey: placeholder
sealed_secrets_scope: namespace-wide # other possible values: strict, cluster-wide, see https://github.com/bitnami-labs/sealed-secrets#scopes