# Default values for rearm-watcher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enabled: true

replicaCount: 1

image:
  repository: registry.relizahub.com/library/rearm-watcher-app:26.03.6@sha256:c14417d0d2e5fe9121e730a011cca0724d5def842e21729ad47e6e24ff46cbbb
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

createServiceAccount: true

namespace: allnamespaces
sender: default

rearmUri: "" # must be defined

create_secret_in_chart: none # or "regular" for plane secret or "sealed" for bitnami sealed secrets
rearmApiId: placeholder
rearmApiKey: placeholder
sealed_secrets_scope: namespace-wide # other possible values: strict, cluster-wide, see https://github.com/bitnami-labs/sealed-secrets#scopes