{{- if eq .Values.create_secret_in_chart "regular"}}
apiVersion: v1
kind: Secret
metadata:
  name: rearm-cd
  namespace: {{ .Release.Namespace }}
  labels:
    app: rearm-cd
type: Opaque
data:
  URI: {{ .Values.rearmUri | b64enc | quote }}
  APIKEYID: {{ .Values.rearmApiId | b64enc | quote }}
  APIKEY: {{ .Values.rearmApiKey | b64enc | quote }}
{{- end }}