mode: STANDALONE # options: STANDALONE, EXISTING_ARGO, NEW_ARGO
imagePullPolicy: IfNotPresent
images:
  rearmcdImage: registry.relizahub.com/library/rearm-cd-app:26.03.12@sha256:db7acd751bb6d67313f7570ec87381393d726ce79f7372aee52f4194f53693b7

enableWatcher: true
backup:
  enabled: false
  schedule: "0 2 * * *" # cron schedule for backup, default is 2 AM daily
  awsRegion: "ca-central-1"
  prefix: "rearm-cd-backup"

storageSize: 1G

create_secret_in_chart: none # regular, none
rearmUri: https://demo.rearmhq.com
rearmApiId: placeholder # instance api id
rearmApiKey: placeholder # instance api key
argoHelmVersion: 6.6.0
