mode: STANDALONE # options: STANDALONE, EXISTING_ARGO, NEW_ARGO
imagePullPolicy: IfNotPresent
images:
  rearmcdImage: registry.relizahub.com/library/rearm-cd-app:26.03.21@sha256:1bc9f9e5f7b82c0fb74ac714a38c2db0dcaf9758289017dfa439ede6b5c4e6eb

enableWatcher: true
watcherHelmVersion: "0.1.11"
watcherHelmChart: "oci://registry.relizahub.com/library/rearm-watcher"
backup:
  enabled: false
  schedule: "0 2 * * *" # cron schedule for backup, default is 2 AM daily
  awsRegion: "ca-central-1"
  prefix: "rearm-cd-backup"

storageSize: 1G

create_secret_in_chart: none # regular, none
rearmUri: https://demo.rearmhq.com
rearmApiId: placeholder # instance api id
rearmApiKey: placeholder # instance api key
argoHelmVersion: 6.6.0
