mode: STANDALONE # options: STANDALONE, EXISTING_ARGO, NEW_ARGO
imagePullPolicy: IfNotPresent
images:
  rearmcdImage: registry.relizahub.com/library/rearm-cd-app:26.03.13@sha256:aa9cd8b25d7765399974b883532d80cf7a37360e66f6771f52b0c279a7a9a979

enableWatcher: true
watcherHelmVersion: "0.1.9"
watcherHelmChart: "oci://registry.relizahub.com/library/rearm-watcher"
backup:
  enabled: false
  schedule: "0 2 * * *" # cron schedule for backup, default is 2 AM daily
  awsRegion: "ca-central-1"
  prefix: "rearm-cd-backup"

storageSize: 1G

create_secret_in_chart: none # regular, none
rearmUri: https://demo.rearmhq.com
rearmApiId: placeholder # instance api id
rearmApiKey: placeholder # instance api key
argoHelmVersion: 6.6.0
