on: [push]

name: Build Docker Image And Submit Metadata To ReARM

jobs:
  build-rearm-cd-app:
    permissions:
      id-token: write
    name: Build ReARM CD App
    runs-on: ubuntu-latest
    steps:
      - name: Build ReARM CD App
        uses: relizaio/rearm-docker-action@5038cf24067c7a71400b633819c3eb97b17aa5c1 # v1.8.0
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com
          image_namespace: registry.relizahub.com/library
          image_name: rearm-cd-app
          rearm_api_id: ${{ secrets.REARM_REARM_CD_API_ID }}
          rearm_api_key: ${{ secrets.REARM_REARM_CD_API_KEY }}
          path: rearm-cd
          platform_architectures: 'linux/amd64,linux/arm64'
          rearm_api_url: https://reliza.rearmhq.com
          enable_sbom: true
          source_code_sbom_type: go
          enable_public_cosign_sigstore: true
          enable_codeql: true
          codeql_language: go
  build-rearm-watcher-app:
    permissions:
      id-token: write
    name: Build ReARM Watcher App
    runs-on: ubuntu-latest
    steps:
      - name: Build ReARM Watcher App
        uses: relizaio/rearm-docker-action@5038cf24067c7a71400b633819c3eb97b17aa5c1 # v1.8.0
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com
          image_namespace: registry.relizahub.com/library
          image_name: rearm-watcher-app
          rearm_api_id: ${{ secrets.REARM_REARM_WATCHER_API_ID }}
          rearm_api_key: ${{ secrets.REARM_REARM_WATCHER_API_KEY }}
          path: rearm-watcher
          platform_architectures: 'linux/amd64'
          rearm_api_url: https://reliza.rearmhq.com
          enable_sbom: true
          source_code_sbom_type: none
          enable_public_cosign_sigstore: true
          enable_codeql: false
  build-rearm-watcher-helm:
    permissions:
      contents: write
      id-token: write
    name: Build ReARM Watcher Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Build ReARM Watcher Helm Chart
        uses: relizaio/rearm-helm-action@5038cf24067c7a71400b633819c3eb97b17aa5c1 # v1.5.0
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com/library
          helm_chart_name: rearm-watcher
          rearm_api_id: ${{ secrets.REARM_REARM_WATCHER_HELM_API_ID }}
          rearm_api_key: ${{ secrets.REARM_REARM_WATCHER_HELM_API_KEY }}
          path: deploy/rearm-watcher-helm
          rearm_api_url: https://reliza.rearmhq.com
          enable_sbom: true
          enable_public_cosign_sigstore: true
  build-rearm-cd-helm:
    permissions:
      contents: write
      id-token: write
    name: Build ReARM CD Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Build ReARM CD Helm Chart
        uses: relizaio/rearm-helm-action@5038cf24067c7a71400b633819c3eb97b17aa5c1 # v1.5.0
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com/library
          helm_chart_name: rearm-cd
          rearm_api_id: ${{ secrets.REARM_REARM_CD_HELM_API_ID }}
          rearm_api_key: ${{ secrets.REARM_REARM_CD_HELM_API_KEY }}
          path: deploy/rearm-cd-helm
          rearm_api_url: https://reliza.rearmhq.com
          enable_sbom: true
          enable_public_cosign_sigstore: true

